### ISSUE TITLE
CMS found

### ISSUE THREAD

**Issue by frostmakk** [ForumPostAssistant/FPA#89] opened 2020-06-09 20:34 UTC
In the old GUI the cms found field looked like 
![image](https://user-images.githubusercontent.com/25645600/84195942-b287fd00-aa9f-11ea-9536-e07e576994e8.png) and ![image](https://user-images.githubusercontent.com/25645600/84195992-c7649080-aa9f-11ea-9c84-1ed72eb488da.png)

Now it looks like 
![image](https://user-images.githubusercontent.com/25645600/84196449-80c36600-aaa0-11ea-8219-66ad0c9b9c83.png) and ![image](https://user-images.githubusercontent.com/25645600/84196503-989aea00-aaa0-11ea-9f1c-052381b1fcf1.png)

Does it look a bit forgotten?

**Comment by sozzled** [comment] 2020-06-09 20:58
Good work, @frostmakk 

Confirmed

![fpa_CMSfound](https://user-images.githubusercontent.com/877778/84198986-c22b3400-aae7-11ea-94c6-419e19d2f39a.jpg)

**Comment by RussW** [comment] 2020-06-09 20:59
yes, it appears that some work on displaying v4 in the GUI still needs to be done

**Comment by RussW** [comment] 2020-06-09 22:40
My error, was looking for the platform version file at the same time as displaying the CMS versioning.

CMS Version info should now be fixed _**but...**_ it seems the platform version file in J4-beta has changed location and is no-longer being found, am looking in to where it can be found now.

**Comment by frostmakk** [comment] 2020-06-09 22:45
Don't think you will find one.
Not sure, but was there some talk about platform / framework / merging / not separate / whatever ?
 
* The power of the Joomla Framework merged into the CMS

**Comment by RussW** [comment] 2020-06-09 22:56
Yes, I believe you are correct, but there must be somewhere that the framework versioning is mentioned, will need to keep working on that particular panel, for the moment, correcting some of my mis-edited code for that panel, it will show "N/A" at the moment because the platform version cannot be found. (maybe should be updated to "Unknown" instead.

**Comment by sozzled** [comment] 2020-06-09 23:04
_OOohhh_ ... Be careful about displaying "unknown".  It may convey the impression that J! 4 is unreliable.  (Well, sure, J! 4 is unreliable at present but I don't want us to get us off-side with the J! 4 team if the FPA script mentioned that).  I anticipate this will prompt Brian calling (again) for the FPA to be axed or, at least, for the J! forum to distance itself from what we're doing.

**Comment by RussW** [comment] 2020-06-09 23:11
"_**Not Found**_" instead? _which is probably a more "accurate" description_

As for external 3rd Party opinion of this project, _do we care?_
_This project is not associated with Joomla!, carries the required disclaimer and can only be shutdown by Github themselves (for some form of breach) or the project members._

**Comment by RussW** [comment] 2020-06-09 23:15
_Out of personal interest..._ 
is this opinion or "call to axe" statement documented anywhere? I'd be interested know the reasons why FPA is considered to be such evil as to after it so hard...

**Comment by sozzled** [comment] 2020-06-09 23:21
Fair enough (and I agree with the overriding sentiment that 3rd-party armchair expert opinion is irrelevant).

I assume, Russ, that you visit the J! forum and read some of these opinions?

We're off-topic.  Getting back to the issue:  we don't know what we don't know and the J! 4 developers are someone schtum about what's happening in tying J! 4 framework → CMS.  But, if FPA v1.5.0 was able to display "in development" (as shown in the image @frostmakk posted), what's changed?

Perhaps a better way of asking the question:  Has J! 4 Beta done something or has FPA v1.6 done something?  I don't know.

**Comment by RussW** [comment] 2020-06-09 23:46
@sozzled only the CMS data was found in the provided image, so I am assuming that the framework data is in error the same as I am seeing on J4

![Screen Shot 2020-06-10 at 9 41 01 am](https://user-images.githubusercontent.com/871931/84211503-d0d11580-aafe-11ea-870a-f2074e63115a.jpg)


Which also now what we see in FPA 1.6.0

![Screen Shot 2020-06-10 at 9 44 33 am](https://user-images.githubusercontent.com/871931/84211614-1857a180-aaff-11ea-8144-f856c097e1ef.jpg)


There was a problem FPA, caused by me for the CMS Info, but the Framework info appears to have changed (as frostmark mentioned)

**Comment by sozzled** [comment] 2020-06-10 00:49
I'm no closer to understanding.  I assume, by inference, that you will look into this and put it on the "todo" list.

**Comment by RussW** [comment] 2020-06-10 01:09
It is on the TODO List : This Issue in particular.

The issue in brief;

- I broke the CMS Version display section in GUI - FIXED

- The PLATFORM Version display is still broken in both the GUI and _Post Output_ as it appears somewhere between J! _Alpha_ and _Beta_ releases, either the Platform Version file has been moved or removed/integrated elsewhere, as yet to be determined - Interim Solution Displays : "_Not Found_" on J4 when we can't determine the path of the versioning.

**Comment by sozzled** [comment] 2020-06-10 01:13
Fair enough.  Probably needs "someone" to ask the J! 4 devs to help out.  Don't ask me: I'm just paddling in the J! 4 pond at the matter and not getting my feet too wet.   I'm already in the gun for expressing my opinions about J! 4.  Just ask Brian who thinks that my commentary is "unhelpful" or insulting all the "hard work" that the J! dev team has been doing.  :laughing:

**Comment by sozzled** [comment] 2020-06-10 03:18
Nice work
![fpa_CMSfound](https://user-images.githubusercontent.com/877778/84223242-d0e00e00-ab1c-11ea-960c-53ef2a85b5f5.jpg)

**Comment by frostmakk** [comment] 2020-06-10 12:55
Yes. Working fine now.
Regarding the other matter with the platform file:
If the framework is now merged into J4, then there is no separate platform, hence N/A is perfectly valid.
Will close this when you on the flip side has woken again.
😄

**Comment by sozzled** [comment] 2020-06-10 15:10
I think I have the answer:  it's not that the framework was merged into the platform, it's the other way around;  the platform has been merged into the framework.  The final J! platform was 13.1 and that looks to be where the "platform" side of things ceased to exist.

- https://magazine.joomla.org/all-issues/march-2013/differences-between-the-joomla-framework-and-joomla-platform

- https://docs.joomla.org/Joomla!_Framework_(CMS_1.5_and_1.6)_vs_Joomla!_Platform

- https://groups.google.com/forum/m/#!msg/joomla-dev-platform/zzNrsCUKCts/hsBntnONm9MJ

Perhaps, because it appears that "platform" has been made obsolete, there's no need to check for it?

**Comment by RussW** [comment] 2020-06-10 23:32
Well researched, thanks @frostmakk - Shall we leave it as "N/A" for J4 at the moment and we can decide how to handle that particular panel going forward at a later date?

**Comment by sozzled** [comment] 2020-06-10 23:49
Fair enough for the present.  As I wrote (as a consequence of doing some background research), it looks like "platform" is a thing of the past.  Will leave it to you.  Cheers.

**Comment by RussW** [comment] 2020-06-11 00:00
Yes, it (plarform) is removed in J4, but still present in J3, so it's handy to generally leave it as it is at the moment _(although it has never been a hugely useful piece of information in troubleshooting)_, and as J4 becomes more common place see if there is some more relevant or useful to replace the older platform information with, seeing as it appears to be "composer" based, maybe the versioning of that, to be sure if that is updated it is at an appropriate version for the J4 release. But for now, we are just showing "N/A" as @frostmakk suggested as this is not only accurate but appropriate in this case.

**Closed as completed** 2020-06-11 05:00 UTC
