### ISSUE TITLE
Multilanguage support removed from FPA

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#88] opened 2020-06-09 20:28 UTC
Looking back over the FPA packages that I have downloaded, going back to FPA v1.2.7(the oldest version that I have) dated 9-May-2017, there is no built-in multilanguage facility.

It appears that the general information (reproduced below) is outdated:

>   ###Multilanguage Version
>
>    This multilanguage branch contains the scripts that create a single, multi language capable, file from a set of PHP files.
>    ####How does it work ?
>
>    It basically scans the PHP code for translatable strings, creates or updates language files, and then builds everything into a single file.
>    ####Advantages:
>
>    By providing language files in a standard language file format, things should become a bit easier for fellow translators.
>    By splitting up the PHP code into several files it should become more maintainable.

It seems that, for the past three years, if someone wanted the FPA in a language other than English, people would have to maintain separate language-specific branches and try to keep things synchronised when the master copy changes.

This begs the question about whether the FPA can be marketed as translatable (simply by having a lookup table/.ini as implied in the quoted text) or not.  I recall that at one time there was a facility to use a lookup table but I can't find a version that performed this.

See also the [README.txt](https://github.com/ForumPostAssistant/FPA/tree/en-GB/Documentation)  that refers to this:
>Language Support:
>English (USA/UK/AU)
>Community language translations may be available.  As translations become available, each localized version will be released into it's own "branch" (EG: fr_FR, de_DE) and will be available for download from the "Download" button (in .tar.gz or .zip format) within the localized branch.  All files that are needed have been automatically added to the download package.

**Comment by frostmakk** [comment] 2020-06-09 20:42
This is not a bug.
There have never been released a multi language version of the FPA.
The multi language stuff mentioned is a branch that never happened.

**Comment by sozzled** [comment] 2020-06-09 20:47
Thanks, @frostmakk.  I agree that there isn't necessarily a bug in the **_software_**, _per se_, but I do recall that there was the ability to lookup translatable strings a while ago and that feature doesn't exist today.  I am saying that we can't "market" the FPA in the terms described in the [README.markdown](https://github.com/ForumPostAssistant/FPA).

In other words, some multilanguage stuff happened a while ago (although I never tried it and I don't have a copy that contains it) but it disappeared.

Perhaps we should just drop the references to "Multilanguage support" where they appear and if in future there's interest in revisiting such a facility then it could be progressed.  Basically, because we've tried to make deployment of the FPA as simple as possible, put everything into one file and tell people that's all they need, we're kind of stuck with English-only at this time.

**Comment by RussW** [comment] 2020-06-09 20:58
Maybe, as the status of "mullti-language support" is in doubt/questionable, the README is updated to remove any mention of it, except a note saying we are looking in to how best to deliver that capability?

And then we start working out what process would be best, and how to achieve it.  @mandville seems to know a little more than most of us about the other language site thing, and maybe asking someone like JM to advise could shed some light?

**Comment by sozzled** [comment] 2020-06-09 21:04
I have some ideas on solving this but no-one is going to like them.  If you would like to contact JM, he'll probably suggest what I would suggest.  It's not so difficult when you have the whole J! framework sitting behind a script to lookup translatable constants; I think we all know how to write our extensions for J! that do this.   The problem that I see is that the FPA script is standalone—it's not installed (and it would be the wrong idea to create a script that someone needed to install) in J!.

**Comment by sozzled** [comment] 2020-06-09 21:06
(One minor "niggle":  might be nicer to rename the file README.markdown to README.md (or README.txt) to "conform" to the file naming conventions used here and in other git repos.  Just a suggestion; no-one's going to lose sleep if this doesn't happen.)

@RussW wrote:
>Maybe, as the status of "mullti-language support" is in doubt/questionable, the README is updated to remove any mention of it, except a note saying we are looking in to how best to deliver that capability?

That would work for me. :+1:

**Comment by RussW** [comment] 2020-06-09 21:19
@sozzled  - sure, go ahead and rename the file if you wish, whether it's .md or .markdown _(which was just legacy for Github and the early days of JTS/FPA)_. And if you would would like to change the multilanguage comments as discussed, I'm happy with that.

The fact FPA is designed to be standalone has always been an issue for translation, especially with the model generally always having been not to drop multple-files, which would be the simplest way.

_**Thinking Out Loud**_ and not knowing how the language site thing works, if it allows remotely pulling their files, an option might be to check for either site or browser language and then pull in the appropriate one from that site, defaulting to the in-built strings if none-found or unable to open the remote file (fopen might be disabled)

But I think, for now, as @sozzled suggests, lets not state something that we aren't doing and then determine a best-case scenario afterwards as a new function/feature.

**Comment by frostmakk** [comment] 2020-06-09 21:42
Have a look at my answer to #29 
Lots of decisions to be made before we get that ball rolling in the right direction.

**Comment by sozzled** [comment] 2020-06-09 21:47
Here is suggested wording for new README for the "documentation" page.  Have a look, change as you see fit, replace the README as you wish.

[readme.txt](https://github.com/ForumPostAssistant/FPA/files/4755034/readme.txt)

I'll look into the project README wording soon.

**Comment by mandville** [comment] 2020-06-09 21:48
crowd in is still the "project" translation tool but there is no maintainer for it. i am not sure how it works, there si also a glip team but i dont want to add another team to my list

**Comment by sozzled** [comment] 2020-06-09 22:04
Here is suggested wording for new README for the project page.

[readme.txt](https://github.com/ForumPostAssistant/FPA/files/4755096/readme.txt)

Similarly, look at it, change as you see fit, and replace the existing README as you want.

**Comment by sozzled** [comment] 2020-06-09 22:07
If CrowdIn is dead in the water, then remove the suggestion (in the README) for people to get involved with it.  I'll leave it up to you guys.

If we're in agreement about the proposed wording changes in the READMEs (plural) we can probably close this issue.  Yes?

**Comment by sozzled** [comment] 2020-06-09 22:44
I just translated the FPA into German (in two seconds).  Of course, it only works if the website's URL is accessible from the internet.

![fpa-de](https://user-images.githubusercontent.com/877778/84208194-80ee5080-aaf6-11ea-866c-86d4f870c3ec.jpg)

What do you think of this as a way out?

**Comment by sozzled** [comment] 2020-06-10 02:32
## Proposal

Drop/abandon attempts to integrate built-in translation from the FPA.  See also https://github.com/ForumPostAssistant/FPA/commit/d2fbee1c9ed772e20a429d375d252f545b2606e7

## Recommendation

Remove all references to "ability" to translate FPA from the source and README files.  If people want to see the FPA translated into their own language they can use _Google Translate_ (as long as the website's URL is accessible on the internet by _Google Translate_).  It's not perfect but it will save our time thinking further about the matters we've discussed..

**Comment by RussW** [comment] 2020-06-10 08:34
Not abandoning multi-lingual support, just deferring until we have determined how best to automate and manage it

**Comment by sozzled** [comment] 2020-06-10 08:40
Please allow other people to have their say.  They may agree with you or they may agree with me.  We lack the resources both in terms of how to provide the feature natively as well as a lack of skilled translators interested enough to contribute to ongoing maintenance).

**Comment by RussW** [comment] 2020-06-10 08:44
I have done nothing of the sort, the item has been discussed, updates have been made to reflect the current situation. The issue has been closed in relation to the topic ...  Not any future devleopment. FFS

**Comment by sozzled** [comment] 2020-06-10 08:47
Where has "the item" been discussed?  With whom?  I think you should take a few moments to have a break and cool down.  I'm not angry (or displaying any attitude) and I don't think I deserve the running characterisation/commentary.

**Comment by sozzled** [comment] 2020-06-10 08:49
You can always kill off my privileges, if you think I'm being playing the raw prawn.  I'm trying to help.  I think we've done good work.  Let's keep things positive.  Thanks.

If you decide to close this item again, don't worry.  I won't re-open it.  :sunglasses:

**Comment by frostmakk** [comment] 2020-06-10 08:56
There are owners, and there are members.
Members advice, owners decide.
This has been decided. Stand down.

**Comment by sozzled** [comment] 2020-06-10 08:58
<=== is suitable chastened and will stand down.  It's OK.
<=== apologises for causing any ruckus.

**Comment by hotmango** [comment] 2020-06-10 09:03
Regards,
Russ



Russ Winter
Head Geek Herder

Email: russw@hotmango.me <mailto:russw@hotmango.me>
Phone: +61 (0)425 713 297 <tel:+61425713297>
Online: www.hotmango.me <https://www.hotmango.me/>
hotmango
web, social media and print
Making You Look Good On the Web
This e-mail message and any accompanying attachments or data may contain information that is confidential and is subject to privilege. If you are not the original or intended recipient, you are notified that receipt of, any use of, permanent storage, dissemination, distribution or copying of this message, attachments or associated data is prohibited by law. If you are not the original or intended recipient or have received this e-mail in error please notify us immediately and delete all material pertaining to this e-mail.

**Comment by RussW** [comment] 2020-06-10 09:06
What ever @sozzled....

Yo get to have your say and make decisions, but you choose to have others do the work for you.
You have complained in the past for not getting **credited**, learn to do a PR and get the credit you are seeking. otherwise, _**it is what it is...**_

Left open as this is your issue and you can choose when to close it....

**Comment by sozzled** [comment] 2020-06-10 09:17
I have NEVER complained about not receiving credit.  NEVER!  Please don't put words in my mouth!

I don't know how to do a PR.  I looked at the article you provided me with and it's scares me.  I installed Git for Windows on my PC but I can't make head nor tail of it.  I consider myself a competent wordsmith and a reasonably good programmer with 50 years of experience.

I have apologised.  It was a sincere apology.  There is no hint of sarcasm in my apology.  It's a genuine apology.  I'm sorry for causing a ruckus.  I'm doing the best I can with the skills—inferior as they may be by other people's standards—to help.  I've enjoyed contributing to the FPA.

I would still like to contribute to the FPA, if you want me to.  But, for goodness sakes, please don't try to educate me about what you think are my motives.  I don't crave attention.  I'm thankful when someone says thanks.  I don't mind if I don't receive public credit for what I do.

I offered a proposal with a recommendation.  There was no vote in favour or against it.

I'm sorry.  Can we leave it at that, please?

**Closed as completed** 2020-06-10 09:18 UTC
Labels: Bug Report
